/* Auto-generated by abi2c.py ¡ª do not edit */
#include "erc20_codec.h"
#include <string.h>

/* Encode balanceOf(address) */
BoatResult encode_balanceOf(const uint8_t account[20], uint8_t **calldata_out, size_t *calldata_len_out)
{
    const char *func_sig = "balanceOf(address)";
    const size_t n_args = 1;
    uint8_t slots[1][32];
    const uint8_t *args[1];
    size_t arg_lens[1];

    boat_evm_abi_encode_address(account, slots[0]);
    args[0] = slots[0];
    arg_lens[0] = 32;

    return boat_evm_abi_encode_func(func_sig, args, arg_lens, n_args, calldata_out, calldata_len_out);
}

/* Decode balanceOf return values */
BoatResult decode_balanceOf(const uint8_t *data, size_t data_len, uint8_t balance[32])
{
    boat_evm_abi_decode_uint256(data, 0, balance);
    return BOAT_SUCCESS;
}

/* Encode transfer(address,uint256) */
BoatResult encode_transfer(const uint8_t to[20], const uint8_t amount[32], uint8_t **calldata_out, size_t *calldata_len_out)
{
    const char *func_sig = "transfer(address,uint256)";
    const size_t n_args = 2;
    uint8_t slots[2][32];
    const uint8_t *args[2];
    size_t arg_lens[2];

    boat_evm_abi_encode_address(to, slots[0]);
    args[0] = slots[0];
    arg_lens[0] = 32;
    boat_evm_abi_encode_uint256(amount, slots[1]);
    args[1] = slots[1];
    arg_lens[1] = 32;

    return boat_evm_abi_encode_func(func_sig, args, arg_lens, n_args, calldata_out, calldata_len_out);
}

/* Decode transfer return values */
BoatResult decode_transfer(const uint8_t *data, size_t data_len, bool *success)
{
    boat_evm_abi_decode_bool(data, 0, success);
    return BOAT_SUCCESS;
}

/* Encode approve(address,uint256) */
BoatResult encode_approve(const uint8_t spender[20], const uint8_t amount[32], uint8_t **calldata_out, size_t *calldata_len_out)
{
    const char *func_sig = "approve(address,uint256)";
    const size_t n_args = 2;
    uint8_t slots[2][32];
    const uint8_t *args[2];
    size_t arg_lens[2];

    boat_evm_abi_encode_address(spender, slots[0]);
    args[0] = slots[0];
    arg_lens[0] = 32;
    boat_evm_abi_encode_uint256(amount, slots[1]);
    args[1] = slots[1];
    arg_lens[1] = 32;

    return boat_evm_abi_encode_func(func_sig, args, arg_lens, n_args, calldata_out, calldata_len_out);
}

/* Decode approve return values */
BoatResult decode_approve(const uint8_t *data, size_t data_len, bool *success)
{
    boat_evm_abi_decode_bool(data, 0, success);
    return BOAT_SUCCESS;
}

/* Encode allowance(address,address) */
BoatResult encode_allowance(const uint8_t owner[20], const uint8_t spender[20], uint8_t **calldata_out, size_t *calldata_len_out)
{
    const char *func_sig = "allowance(address,address)";
    const size_t n_args = 2;
    uint8_t slots[2][32];
    const uint8_t *args[2];
    size_t arg_lens[2];

    boat_evm_abi_encode_address(owner, slots[0]);
    args[0] = slots[0];
    arg_lens[0] = 32;
    boat_evm_abi_encode_address(spender, slots[1]);
    args[1] = slots[1];
    arg_lens[1] = 32;

    return boat_evm_abi_encode_func(func_sig, args, arg_lens, n_args, calldata_out, calldata_len_out);
}

/* Decode allowance return values */
BoatResult decode_allowance(const uint8_t *data, size_t data_len, uint8_t remaining[32])
{
    boat_evm_abi_decode_uint256(data, 0, remaining);
    return BOAT_SUCCESS;
}

/* Encode transferFrom(address,address,uint256) */
BoatResult encode_transferFrom(const uint8_t from[20], const uint8_t to[20], const uint8_t amount[32], uint8_t **calldata_out, size_t *calldata_len_out)
{
    const char *func_sig = "transferFrom(address,address,uint256)";
    const size_t n_args = 3;
    uint8_t slots[3][32];
    const uint8_t *args[3];
    size_t arg_lens[3];

    boat_evm_abi_encode_address(from, slots[0]);
    args[0] = slots[0];
    arg_lens[0] = 32;
    boat_evm_abi_encode_address(to, slots[1]);
    args[1] = slots[1];
    arg_lens[1] = 32;
    boat_evm_abi_encode_uint256(amount, slots[2]);
    args[2] = slots[2];
    arg_lens[2] = 32;

    return boat_evm_abi_encode_func(func_sig, args, arg_lens, n_args, calldata_out, calldata_len_out);
}

/* Decode transferFrom return values */
BoatResult decode_transferFrom(const uint8_t *data, size_t data_len, bool *success)
{
    boat_evm_abi_decode_bool(data, 0, success);
    return BOAT_SUCCESS;
}

