/* Auto-generated by abi2c.py ¡ª do not edit */
#ifndef ERC20_CODEC_H
#define ERC20_CODEC_H

#include "boat_evm.h"

#ifdef __cplusplus
extern "C" {
#endif

BoatResult encode_balanceOf(const uint8_t account[20], uint8_t **calldata_out, size_t *calldata_len_out);
BoatResult decode_balanceOf(const uint8_t *data, size_t data_len, uint8_t balance[32]);

BoatResult encode_transfer(const uint8_t to[20], const uint8_t amount[32], uint8_t **calldata_out, size_t *calldata_len_out);
BoatResult decode_transfer(const uint8_t *data, size_t data_len, bool *success);

BoatResult encode_approve(const uint8_t spender[20], const uint8_t amount[32], uint8_t **calldata_out, size_t *calldata_len_out);
BoatResult decode_approve(const uint8_t *data, size_t data_len, bool *success);

BoatResult encode_allowance(const uint8_t owner[20], const uint8_t spender[20], uint8_t **calldata_out, size_t *calldata_len_out);
BoatResult decode_allowance(const uint8_t *data, size_t data_len, uint8_t remaining[32]);

BoatResult encode_transferFrom(const uint8_t from[20], const uint8_t to[20], const uint8_t amount[32], uint8_t **calldata_out, size_t *calldata_len_out);
BoatResult decode_transferFrom(const uint8_t *data, size_t data_len, bool *success);

#ifdef __cplusplus
}
#endif

#endif /* ERC20_CODEC_H */
